// <auto-generated />
using System;
using Cms.Framework.Infrastructure;
using Cms.Poc.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cms.Poc.Api.Migrations
{
    [DbContext(typeof(CmsDbContext<ContentTypeKey>))]
    [Migration("20260921104403_AddedUserTracking")]
    partial class AddedUserTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Cms.Framework.Generated.EventContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Language")
                        .IsUnique();

                    b.ToTable("EventContentTranslations", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RootId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EventContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Language")
                        .IsUnique();

                    b.ToTable("NewsContentTranslations", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedContent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RootId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("NewsContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Language")
                        .IsUnique();

                    b.ToTable("SpecialNewsContentTranslations", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedContent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RootId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SpecialNewsContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeKey");

                    b.HasIndex("Name");

                    b.ToTable("ContentRoots", (string)null);
                });

            modelBuilder.Entity("Cms.Poc.Domain.EventContent", b =>
                {
                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\n    r.Id AS Id,\n    r.Name AS Name,\n    t.Language AS Language,\n    v.VersionNumber AS VersionNumber,\n    v.Created AS Created,\n    v.StartPublish AS StartPublish,\n    v.StopPublish AS StopPublish,\n    v.CreatedBy AS CreatedBy,\n    v.PublishedBy AS PublishedBy,\n    v.StartDate AS StartDate,\n    t.Title AS Title,\n    t.Description AS Description\nFROM ContentRoots r\nJOIN EventContentVersions v ON v.RootId = r.Id\n    AND v.VersionNumber = (SELECT MAX(v2.VersionNumber) FROM EventContentVersions v2 WHERE v2.RootId = r.Id)\nJOIN EventContentTranslations t ON t.VersionId = v.Id\nWHERE r.ContentTypeKey = 'EventContent'");
                });

            modelBuilder.Entity("Cms.Poc.Domain.NewsContent", b =>
                {
                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedContent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\n    r.Id AS Id,\n    r.Name AS Name,\n    t.Language AS Language,\n    v.VersionNumber AS VersionNumber,\n    v.Created AS Created,\n    v.StartPublish AS StartPublish,\n    v.StopPublish AS StopPublish,\n    v.CreatedBy AS CreatedBy,\n    v.PublishedBy AS PublishedBy,\n    v.RelatedContent AS RelatedContent,\n    t.Heading AS Heading,\n    t.Body AS Body\nFROM ContentRoots r\nJOIN NewsContentVersions v ON v.RootId = r.Id\n    AND v.VersionNumber = (SELECT MAX(v2.VersionNumber) FROM NewsContentVersions v2 WHERE v2.RootId = r.Id)\nJOIN NewsContentTranslations t ON t.VersionId = v.Id\nWHERE r.ContentTypeKey = 'NewsContent'");
                });

            modelBuilder.Entity("Cms.Poc.Domain.SpecialNewsContent", b =>
                {
                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedContent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\n    r.Id AS Id,\n    r.Name AS Name,\n    t.Language AS Language,\n    v.VersionNumber AS VersionNumber,\n    v.Created AS Created,\n    v.StartPublish AS StartPublish,\n    v.StopPublish AS StopPublish,\n    v.CreatedBy AS CreatedBy,\n    v.PublishedBy AS PublishedBy,\n    v.RelatedContent AS RelatedContent,\n    t.Heading AS Heading,\n    t.Body AS Body,\n    t.SpecialBody AS SpecialBody\nFROM ContentRoots r\nJOIN SpecialNewsContentVersions v ON v.RootId = r.Id\n    AND v.VersionNumber = (SELECT MAX(v2.VersionNumber) FROM SpecialNewsContentVersions v2 WHERE v2.RootId = r.Id)\nJOIN SpecialNewsContentTranslations t ON t.VersionId = v.Id\nWHERE r.ContentTypeKey = 'SpecialNewsContent'");
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentTranslation", b =>
                {
                    b.HasOne("Cms.Framework.Generated.EventContentVersion", "Version")
                        .WithMany("Translations")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentVersion", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentTranslation", b =>
                {
                    b.HasOne("Cms.Framework.Generated.NewsContentVersion", "Version")
                        .WithMany("Translations")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentVersion", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentTranslation", b =>
                {
                    b.HasOne("Cms.Framework.Generated.SpecialNewsContentVersion", "Version")
                        .WithMany("Translations")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentVersion", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentVersion", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentVersion", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentVersion", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
