// <auto-generated />
using System;
using Cms.Framework.Infrastructure;
using Cms.Poc.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cms.Poc.Api.Migrations
{
    [DbContext(typeof(CmsDbContext<ContentTypeKey>))]
    [Migration("20260921080357_Removed_ContentType")]
    partial class Removed_ContentType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Cms.Framework.Generated.EventContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Language")
                        .IsUnique();

                    b.ToTable("EventContentTranslations", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RootId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EventContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Language")
                        .IsUnique();

                    b.ToTable("NewsContentTranslations", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RootId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("NewsContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Infrastructure.ContentRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeKey");

                    b.HasIndex("Name");

                    b.ToTable("ContentRoots", (string)null);
                });

            modelBuilder.Entity("Cms.Poc.Domain.EventContent", b =>
                {
                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\r\n    r.Id AS Id,\r\n    r.Name AS Name,\r\n    t.Language AS Language,\r\n    v.VersionNumber AS VersionNumber,\r\n    v.Created AS Created,\r\n    v.StartPublish AS StartPublish,\r\n    v.StopPublish AS StopPublish,\n    v.StartDate AS StartDate,\n    t.Title AS Title,\n    t.Description AS Description\r\nFROM ContentRoots r\r\nJOIN EventContentVersions v ON v.RootId = r.Id\r\n    AND v.VersionNumber = (SELECT MAX(v2.VersionNumber) FROM EventContentVersions v2 WHERE v2.RootId = r.Id)\r\nJOIN EventContentTranslations t ON t.VersionId = v.Id\r\nWHERE r.ContentTypeKey = 'EventContent'");
                });

            modelBuilder.Entity("Cms.Poc.Domain.NewsContent", b =>
                {
                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedContentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\r\n    r.Id AS Id,\r\n    r.Name AS Name,\r\n    t.Language AS Language,\r\n    v.VersionNumber AS VersionNumber,\r\n    v.Created AS Created,\r\n    v.StartPublish AS StartPublish,\r\n    v.StopPublish AS StopPublish,\n    v.RelatedContentId AS RelatedContentId,\n    t.Heading AS Heading,\n    t.Body AS Body\r\nFROM ContentRoots r\r\nJOIN NewsContentVersions v ON v.RootId = r.Id\r\n    AND v.VersionNumber = (SELECT MAX(v2.VersionNumber) FROM NewsContentVersions v2 WHERE v2.RootId = r.Id)\r\nJOIN NewsContentTranslations t ON t.VersionId = v.Id\r\nWHERE r.ContentTypeKey = 'NewsContent'");
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentTranslation", b =>
                {
                    b.HasOne("Cms.Framework.Generated.EventContentVersion", "Version")
                        .WithMany("Translations")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentVersion", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentTranslation", b =>
                {
                    b.HasOne("Cms.Framework.Generated.NewsContentVersion", "Version")
                        .WithMany("Translations")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentVersion", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentVersion", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentVersion", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
