// <auto-generated />
using System;
using Cms.Framework.Infrastructure;
using Cms.Poc.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cms.Poc.Api.Migrations
{
    [DbContext(typeof(CmsDbContext<ContentTypeKey>))]
    [Migration("20260923120033_AddIntroProperty")]
    partial class AddIntroProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Cms.Framework.Generated.EventContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RootId", "Language", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EventContentTranslations", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RootId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EventContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RootId", "Language", "VersionNumber")
                        .IsUnique();

                    b.ToTable("NewsContentTranslations", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedContent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RootId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("NewsContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RootId", "Language", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SpecialNewsContentTranslations", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedContent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RootId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SpecialNewsContentVersions", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeKey");

                    b.ToTable("ContentRoots", (string)null);
                });

            modelBuilder.Entity("Cms.Framework.Infrastructure.Settings.CmsSettingEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("CmsSettings", (string)null);
                });

            modelBuilder.Entity("Cms.Poc.Domain.EventContent", b =>
                {
                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\n    r.Id AS Id,\n    v.Name AS Name,\n    r.MasterLanguage AS Language,\n    r.MasterLanguage AS MasterLanguage,\n    v.VersionNumber AS VersionNumber,\n    v.Created AS Created,\n    v.StartPublish AS StartPublish,\n    v.StopPublish AS StopPublish,\n    v.CreatedBy AS CreatedBy,\n    v.PublishedBy AS PublishedBy,\n    v.StartDate AS StartDate,\n    v.Title AS Title,\n    v.Intro AS Intro,\n    v.Description AS Description\nFROM ContentRoots r\nJOIN EventContentVersions v ON v.RootId = r.Id\n    AND v.VersionNumber = (SELECT MAX(v2.VersionNumber) FROM EventContentVersions v2 WHERE v2.RootId = r.Id)\nWHERE r.ContentTypeKey = 'EventContent'\n\nUNION ALL\n\nSELECT\n    r.Id AS Id,\n    t.Name AS Name,\n    t.Language AS Language,\n    r.MasterLanguage AS MasterLanguage,\n    t.VersionNumber AS VersionNumber,\n    t.Created AS Created,\n    t.StartPublish AS StartPublish,\n    t.StopPublish AS StopPublish,\n    t.CreatedBy AS CreatedBy,\n    t.PublishedBy AS PublishedBy,\n    mv.StartDate AS StartDate,\n    t.Title AS Title,\n    t.Intro AS Intro,\n    t.Description AS Description\nFROM ContentRoots r\nJOIN EventContentTranslations t ON t.RootId = r.Id\n    AND t.VersionNumber = (SELECT MAX(t2.VersionNumber) FROM EventContentTranslations t2 WHERE t2.RootId = r.Id AND t2.Language = t.Language)\nJOIN EventContentVersions mv ON mv.Id = (COALESCE(\n        (SELECT v3.Id FROM EventContentVersions v3\n         WHERE v3.RootId = r.Id AND v3.StartPublish IS NOT NULL AND datetime(v3.StartPublish) <= datetime('now') AND (v3.StopPublish IS NULL OR datetime(v3.StopPublish) > datetime('now'))\n         ORDER BY v3.StartPublish DESC LIMIT 1),\n        (SELECT v4.Id FROM EventContentVersions v4 WHERE v4.RootId = r.Id ORDER BY v4.VersionNumber DESC LIMIT 1)\n    ))\nWHERE r.ContentTypeKey = 'EventContent'");
                });

            modelBuilder.Entity("Cms.Poc.Domain.NewsContent", b =>
                {
                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedContent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\n    r.Id AS Id,\n    v.Name AS Name,\n    r.MasterLanguage AS Language,\n    r.MasterLanguage AS MasterLanguage,\n    v.VersionNumber AS VersionNumber,\n    v.Created AS Created,\n    v.StartPublish AS StartPublish,\n    v.StopPublish AS StopPublish,\n    v.CreatedBy AS CreatedBy,\n    v.PublishedBy AS PublishedBy,\n    v.RelatedContent AS RelatedContent,\n    v.Heading AS Heading,\n    v.Intro AS Intro,\n    v.Body AS Body\nFROM ContentRoots r\nJOIN NewsContentVersions v ON v.RootId = r.Id\n    AND v.VersionNumber = (SELECT MAX(v2.VersionNumber) FROM NewsContentVersions v2 WHERE v2.RootId = r.Id)\nWHERE r.ContentTypeKey = 'NewsContent'\n\nUNION ALL\n\nSELECT\n    r.Id AS Id,\n    t.Name AS Name,\n    t.Language AS Language,\n    r.MasterLanguage AS MasterLanguage,\n    t.VersionNumber AS VersionNumber,\n    t.Created AS Created,\n    t.StartPublish AS StartPublish,\n    t.StopPublish AS StopPublish,\n    t.CreatedBy AS CreatedBy,\n    t.PublishedBy AS PublishedBy,\n    mv.RelatedContent AS RelatedContent,\n    t.Heading AS Heading,\n    t.Intro AS Intro,\n    t.Body AS Body\nFROM ContentRoots r\nJOIN NewsContentTranslations t ON t.RootId = r.Id\n    AND t.VersionNumber = (SELECT MAX(t2.VersionNumber) FROM NewsContentTranslations t2 WHERE t2.RootId = r.Id AND t2.Language = t.Language)\nJOIN NewsContentVersions mv ON mv.Id = (COALESCE(\n        (SELECT v3.Id FROM NewsContentVersions v3\n         WHERE v3.RootId = r.Id AND v3.StartPublish IS NOT NULL AND datetime(v3.StartPublish) <= datetime('now') AND (v3.StopPublish IS NULL OR datetime(v3.StopPublish) > datetime('now'))\n         ORDER BY v3.StartPublish DESC LIMIT 1),\n        (SELECT v4.Id FROM NewsContentVersions v4 WHERE v4.RootId = r.Id ORDER BY v4.VersionNumber DESC LIMIT 1)\n    ))\nWHERE r.ContentTypeKey = 'NewsContent'");
                });

            modelBuilder.Entity("Cms.Poc.Domain.SpecialNewsContent", b =>
                {
                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MasterLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedContent")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartPublish")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopPublish")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\n    r.Id AS Id,\n    v.Name AS Name,\n    r.MasterLanguage AS Language,\n    r.MasterLanguage AS MasterLanguage,\n    v.VersionNumber AS VersionNumber,\n    v.Created AS Created,\n    v.StartPublish AS StartPublish,\n    v.StopPublish AS StopPublish,\n    v.CreatedBy AS CreatedBy,\n    v.PublishedBy AS PublishedBy,\n    v.RelatedContent AS RelatedContent,\n    v.Heading AS Heading,\n    v.Intro AS Intro,\n    v.Body AS Body,\n    v.SpecialBody AS SpecialBody\nFROM ContentRoots r\nJOIN SpecialNewsContentVersions v ON v.RootId = r.Id\n    AND v.VersionNumber = (SELECT MAX(v2.VersionNumber) FROM SpecialNewsContentVersions v2 WHERE v2.RootId = r.Id)\nWHERE r.ContentTypeKey = 'SpecialNewsContent'\n\nUNION ALL\n\nSELECT\n    r.Id AS Id,\n    t.Name AS Name,\n    t.Language AS Language,\n    r.MasterLanguage AS MasterLanguage,\n    t.VersionNumber AS VersionNumber,\n    t.Created AS Created,\n    t.StartPublish AS StartPublish,\n    t.StopPublish AS StopPublish,\n    t.CreatedBy AS CreatedBy,\n    t.PublishedBy AS PublishedBy,\n    mv.RelatedContent AS RelatedContent,\n    t.Heading AS Heading,\n    t.Intro AS Intro,\n    t.Body AS Body,\n    t.SpecialBody AS SpecialBody\nFROM ContentRoots r\nJOIN SpecialNewsContentTranslations t ON t.RootId = r.Id\n    AND t.VersionNumber = (SELECT MAX(t2.VersionNumber) FROM SpecialNewsContentTranslations t2 WHERE t2.RootId = r.Id AND t2.Language = t.Language)\nJOIN SpecialNewsContentVersions mv ON mv.Id = (COALESCE(\n        (SELECT v3.Id FROM SpecialNewsContentVersions v3\n         WHERE v3.RootId = r.Id AND v3.StartPublish IS NOT NULL AND datetime(v3.StartPublish) <= datetime('now') AND (v3.StopPublish IS NULL OR datetime(v3.StopPublish) > datetime('now'))\n         ORDER BY v3.StartPublish DESC LIMIT 1),\n        (SELECT v4.Id FROM SpecialNewsContentVersions v4 WHERE v4.RootId = r.Id ORDER BY v4.VersionNumber DESC LIMIT 1)\n    ))\nWHERE r.ContentTypeKey = 'SpecialNewsContent'");
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentTranslation", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.EventContentVersion", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentTranslation", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.NewsContentVersion", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentTranslation", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Cms.Framework.Generated.SpecialNewsContentVersion", b =>
                {
                    b.HasOne("Cms.Framework.Infrastructure.ContentRoot<Cms.Poc.Domain.ContentTypeKey>", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Root");
                });
#pragma warning restore 612, 618
        }
    }
}
